name: raven
description: A small color pallet for flutter apps
version: 1.0.0
homepage: https://github.com/gizet/raven
repository: https://github.com/gizet/raven

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
